import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

ThemeData lightModeTheme = FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xff3498db),
    primaryContainer: Color(0xff2c3e50),
    secondary: Color(0xffe74c3c),
    secondaryContainer: Color(0xffc0392b),
    tertiary: Color(0xfff39c12),
    tertiaryContainer: Color(0xffd35400),
    appBarColor: Color(0xff2c3e50),
    error: Color(0xffc0392b),
  ),
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 7,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 10,
    blendOnColors: false,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    textButtonRadius: 10.0,
    filledButtonRadius: 10.0,
    elevatedButtonRadius: 10.0,
    outlinedButtonRadius: 10.0,
    toggleButtonsRadius: 10.0,
    segmentedButtonSchemeColor: SchemeColor.primary,
    sliderTrackHeight: 10,
    inputDecoratorSchemeColor: SchemeColor.surface,
    inputDecoratorBorderSchemeColor: SchemeColor.onSurface,
    inputDecoratorRadius: 10.0,
    inputCursorSchemeColor: SchemeColor.onSurface,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
    snackBarRadius: 10,
    snackBarBackgroundSchemeColor: SchemeColor.inversePrimary,
    snackBarActionSchemeColor: SchemeColor.onPrimary,
    tabBarItemSchemeColor: SchemeColor.primary,
    tabBarUnselectedItemSchemeColor: SchemeColor.outline,
    drawerRadius: 35.0,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.outline,
    bottomNavigationBarMutedUnselectedLabel: false,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.outline,
    bottomNavigationBarMutedUnselectedIcon: false,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarIndicatorSchemeColor: SchemeColor.primary,
    navigationBarIndicatorOpacity: 0.80,
    navigationRailIndicatorSchemeColor: SchemeColor.primary,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  fontFamily: 'Oxygen',
);
ThemeData darkModeTheme = FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xff4a90e2),
    primaryContainer: Color(0xff002f6c),
    secondary: Color(0xffe94e77),
    secondaryContainer: Color(0xff8e0045),
    tertiary: Color(0xff50e3c2),
    tertiaryContainer: Color(0xff00796b),
    appBarColor: Color(0xff002f6c),
    error: Color(0xffd32f2f),
  ),
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 13,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 20,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    textButtonRadius: 10.0,
    filledButtonRadius: 10.0,
    elevatedButtonRadius: 10.0,
    outlinedButtonRadius: 10.0,
    toggleButtonsRadius: 10.0,
    segmentedButtonSchemeColor: SchemeColor.primary,
    sliderTrackHeight: 10,
    inputDecoratorSchemeColor: SchemeColor.surface,
    inputDecoratorBorderSchemeColor: SchemeColor.onSurface,
    inputDecoratorRadius: 10.0,
    inputCursorSchemeColor: SchemeColor.onSurface,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
    snackBarRadius: 10,
    snackBarBackgroundSchemeColor: SchemeColor.inversePrimary,
    snackBarActionSchemeColor: SchemeColor.onPrimary,
    tabBarItemSchemeColor: SchemeColor.primary,
    tabBarUnselectedItemSchemeColor: SchemeColor.outline,
    drawerRadius: 35.0,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.outline,
    bottomNavigationBarMutedUnselectedLabel: false,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.outline,
    bottomNavigationBarMutedUnselectedIcon: false,
    navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
    navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarIndicatorSchemeColor: SchemeColor.primary,
    navigationBarIndicatorOpacity: 0.80,
    navigationRailIndicatorSchemeColor: SchemeColor.primary,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  fontFamily: 'Oxygen',
);
